spring.application.name=grupoSenda
server.port=8081

# ==== Conexión a H2 ====
spring.datasource.url=jdbc:h2:mem:rutas
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ==== Configuración de JPA / Hibernate ====
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true

# ==== Consola Web de H2 ====
# Permite entrar a http://localhost:8080/h2-console para ver la base de datos
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.properties.hibernate.format_sql=true

spring.output.ansi.enabled=ALWAYS